# Generated by Django 6.0.7 on 2026-07-14 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('icon', models.CharField(max_length=60)),
                ('accent', models.CharField(default='primary', max_length=20)),
                ('unlocked', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('level', models.PositiveIntegerField(default=1)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('next_level_xp', models.PositiveIntegerField(default=1000)),
                ('elite_points', models.PositiveIntegerField(default=0)),
                ('global_rank', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('detail', models.CharField(max_length=160)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(default='fitness_center', max_length=60)),
                ('days_left', models.PositiveIntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('icon', models.CharField(default='fitness_center', max_length=60)),
                ('accent', models.CharField(default='cyan', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('points', models.PositiveIntegerField()),
                ('medal', models.CharField(blank=True, max_length=20)),
                ('is_current_user', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('level', models.PositiveIntegerField(default=1)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('accent', models.CharField(default='indigo', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date_label', models.CharField(max_length=30)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('tag', models.CharField(max_length=40)),
                ('icon', models.CharField(default='fitness_center', max_length=60)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('goal', models.CharField(choices=[('forca', 'Forca'), ('hipertrofia', 'Hipertrofia'), ('endurance', 'Endurance'), ('mobilidade', 'Mobilidade'), ('hiit', 'HIIT')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('calories', models.PositiveIntegerField(default=300)),
                ('image_url', models.URLField(blank=True)),
                ('level', models.CharField(default='Intermediario', max_length=60)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('is_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('focus', models.CharField(choices=[('forca', 'Forca'), ('hipertrofia', 'Hipertrofia'), ('endurance', 'Endurance'), ('mobilidade', 'Mobilidade'), ('hiit', 'HIIT')], max_length=20)),
                ('primary_muscle', models.CharField(max_length=120)),
                ('secondary_muscles', models.CharField(blank=True, max_length=180)),
                ('default_sets', models.PositiveIntegerField(default=3)),
                ('default_reps', models.CharField(default='10', max_length=40)),
                ('rest_seconds', models.PositiveIntegerField(default=60)),
                ('tutorial_duration', models.CharField(default='02:00', max_length=10)),
                ('image_url', models.URLField(blank=True)),
                ('anatomy_image_url', models.URLField(blank=True)),
                ('instructions', models.JSONField(blank=True, default=list)),
                ('is_run', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='dashboard.exercisecategory')),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('sets', models.PositiveIntegerField(default=3)),
                ('reps', models.CharField(default='10', max_length=40)),
                ('rest_seconds', models.PositiveIntegerField(default=60)),
                ('notes', models.CharField(blank=True, max_length=180)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routine_items', to='dashboard.exercise')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.workoutroutine')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('detail', models.CharField(blank=True, max_length=120)),
                ('is_today', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.workoutroutine')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
