# Generated by Django 6.0.7 on 2026-07-14 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=220)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dashboard.workoutroutine')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=True)),
                ('load_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sets_done', models.PositiveIntegerField(default=0)),
                ('reps_done', models.CharField(blank=True, max_length=40)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='dashboard.workoutsession')),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_logs', to='dashboard.workoutexercise')),
            ],
            options={
                'ordering': ['workout_exercise__order', 'id'],
            },
        ),
    ]
