# Generated by Django 6.0.7 on 2026-07-14 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_workoutsession_workoutsessionexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsessionexercise',
            name='workout_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='dashboard.workoutexercise'),
        ),
    ]
