# Generated by Django 6.0.7 on 2026-07-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutroutine',
            name='training_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
