# Generated by Django 6.0.7 on 2026-07-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_userxpevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsessionexercise',
            name='rpe',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
